### ISSUE TITLE
Potential bug in `xarray_reduce`

### ISSUE THREAD

**Issue by andersy005** [dcherian/dask_groupby#20]
When I try using the `xarray_reduce` interface with the following 

```python
xarray_reduce(ds.Tair, ds.time.dt.month, func='mean')
```

I get an UnboundLocalError.:

```python
In [19]: xarray_reduce(ds.Tair, ds.time.dt.month, func='mean')
<xarray.DataArray 'month' (time: 36)>
array([ 9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,
        7,  8])
Coordinates:
  * time     (time) object 1980-09-16 12:00:00 ... 1983-08-17 00:00:00
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-19-b8f0e0a131da> in <module>
----> 1 xarray_reduce(ds.Tair, ds.time.dt.month, func='mean')

~/devel/pydata/dask_groupby/dask_groupby/xarray.py in xarray_reduce(obj, func, expected_groups, bins, dim, split_out, fill_value, *by)
     48 
     49     group_names = tuple(g.name for g in by)
---> 50     group_sizes = dict(zip(group_names, group_shape))
     51     indims = tuple(obj.dims)
     52     otherdims = tuple(d for d in indims if d not in dim)

UnboundLocalError: local variable 'group_shape' referenced before assignment

```

It appears that `group_shape` is only defined when using multiple groupers

https://github.com/dcherian/dask_groupby/blob/cab3b5bc3355e7934fe60029fc1063b6ed2f0a2f/dask_groupby/xarray.py#L39-L41

@dcherian, Am I missing something?

**Comment by dcherian** [comment]
Nah, that is a bug. I basically stopped partway through implementing grouping by multiple variables, so there will be bugs in xarray interfaces

**Comment by andersy005** [comment]
Okay... That's good to know... I was trying to see if I could use `xarray_reduce` since it accepts `dim` keyword which `xarray_groupby_reduce` doesn't support... I will look into this

**Comment by dcherian** [comment]
I mean  you could just as well use `xarray_reduce` that's what we want eventually. I thought it'd be easier to start with `xarray_groupby_reduce` but they're not so different. `xarray_reduce` allows access to all features; much more than what the current groupby lets you do
